'use client'

import { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { ImageIcon, RefreshCw, Loader2, Maximize2 } from 'lucide-react'

interface LessonImageProps {
    topic: string
    context?: string
    className?: string
    autoGenerate?: boolean
}

export function LessonImage({ topic, context, className, autoGenerate = true }: LessonImageProps) {
    const [imageUrl, setImageUrl] = useState<string | null>(null)
    const [isLoading, setIsLoading] = useState(false)
    const [error, setError] = useState<string | null>(null)
    const [isExpanded, setIsExpanded] = useState(false)
    const hasAutoGenerated = useState(false)

    const generateImage = async () => {
        setIsLoading(true)
        setError(null)

        try {
            const response = await fetch('/api/learn/generate-image', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ topic, context })
            })

            if (!response.ok) {
                throw new Error('Failed to generate image')
            }

            const data = await response.json()
            setImageUrl(data.imageUrl)
        } catch (err) {
            console.error('Image generation error:', err)
            setError('Could not generate image. Try again!')
        } finally {
            setIsLoading(false)
        }
    }

    // Auto-generate on mount
    useEffect(() => {
        if (autoGenerate && !imageUrl && !isLoading && !hasAutoGenerated[0]) {
            hasAutoGenerated[1](true)
            // Delay to let audio start first
            const timer = setTimeout(() => {
                generateImage()
            }, 2000)
            return () => clearTimeout(timer)
        }
    }, [topic, autoGenerate])

    return (
        <div className={`lesson-image-container ${className}`}>
            {!imageUrl && !isLoading && (
                <div className="flex flex-col items-center justify-center p-8 bg-gradient-to-br from-purple-50 to-blue-50 rounded-xl border-2 border-dashed border-purple-200">
                    <ImageIcon className="w-12 h-12 text-purple-400 mb-4" />
                    <p className="text-slate-600 mb-4 text-center">
                        🎨 Want a visual explanation of <strong>{topic}</strong>?
                    </p>
                    <Button
                        onClick={generateImage}
                        className="bg-gradient-to-r from-purple-500 to-blue-500 hover:from-purple-600 hover:to-blue-600"
                    >
                        <ImageIcon className="w-4 h-4 mr-2" />
                        Generate Diagram
                    </Button>
                </div>
            )}

            {isLoading && (
                <div className="flex flex-col items-center justify-center p-8 bg-gradient-to-br from-purple-50 to-blue-50 rounded-xl">
                    <Loader2 className="w-12 h-12 text-purple-500 animate-spin mb-4" />
                    <p className="text-slate-600">🎨 Creating your visual explanation...</p>
                    <p className="text-sm text-slate-500 mt-2">This may take 10-20 seconds</p>
                </div>
            )}

            {error && (
                <div className="flex flex-col items-center justify-center p-8 bg-red-50 rounded-xl border border-red-200">
                    <p className="text-red-600 mb-4">{error}</p>
                    <Button
                        variant="outline"
                        onClick={generateImage}
                    >
                        <RefreshCw className="w-4 h-4 mr-2" />
                        Try Again
                    </Button>
                </div>
            )}

            {imageUrl && !isLoading && (
                <div className="relative">
                    <div className={`overflow-hidden rounded-xl border shadow-lg transition-all ${isExpanded ? 'fixed inset-4 z-50 bg-white p-4' : ''}`}>
                        {isExpanded && (
                            <div className="absolute inset-0 bg-black/50 -z-10" onClick={() => setIsExpanded(false)} />
                        )}
                        <div className="flex items-center justify-between p-3 bg-gradient-to-r from-purple-500 to-blue-500 text-white">
                            <span className="font-medium">🖼️ Visual Explanation: {topic}</span>
                            <div className="flex gap-2">
                                <Button
                                    size="sm"
                                    variant="ghost"
                                    className="text-white hover:bg-white/20"
                                    onClick={() => setIsExpanded(!isExpanded)}
                                >
                                    <Maximize2 className="w-4 h-4" />
                                </Button>
                                <Button
                                    size="sm"
                                    variant="ghost"
                                    className="text-white hover:bg-white/20"
                                    onClick={generateImage}
                                >
                                    <RefreshCw className="w-4 h-4" />
                                </Button>
                            </div>
                        </div>
                        <img
                            src={imageUrl}
                            alt={`Visual explanation of ${topic}`}
                            className={`w-full ${isExpanded ? 'max-h-[80vh] object-contain' : 'max-h-96 object-cover'}`}
                            onError={() => setError('Image failed to load')}
                        />
                        <div className="p-2 bg-slate-50 text-xs text-slate-500 text-center">
                            🎨 AI-generated educational illustration • Click refresh for a different visualization
                        </div>
                    </div>
                </div>
            )}
        </div>
    )
}
